apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $value := .Values.secretEnvs }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- range $key, $value := merge .Values.secretFiles .Values.tls.files }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
